### ISSUE TITLE
链接不上百度SCS的Redis

### ISSUE THREAD

**Issue by itwmike** [caoxinyu/RedisClient#64]
百度 SCS Redis的地址格式为：redis.**********.scs.bj.baidubce.com，链接出现 ERR unkonwn command 'config' 。。
求教是什么问题？

**Comment by caoxinyu** [comment]
应该是设置替换了CONFIG命令

**Comment by kuainiao** [comment]
腾讯redis也没有CONFIG命令，怎样设置去掉CONFIG命令？

**Comment by caoxinyu** [comment]
后台配置rename-command CONFIG

**Comment by kuainiao** [comment]
后台不支持这个命令，之前phpredisadmin也是要用到这个命令，加上'databases' => 16,这个配置后就避开config命令，不知道RedisClient要配置什么才避开这个命令。

**Comment by caoxinyu** [comment]
Command renaming.

 It is possible to change the name of dangerous commands in a shared
 environment. For instance the CONFIG command may be renamed into something
 hard to guess so that it will still be available for internal-use tools
 but not available for general clients.

 Example:

 rename-command CONFIG b840fc02d524045429941cc15f59e41cb7be6c52

 It is also possible to completely kill a command by renaming it into
 an empty string:

 rename-command CONFIG ""

**Comment by kuainiao** [comment]
这个是腾讯那边的redis服务，不可以修改这个配置，应该是客户端要获取databases 参数，然后redis服务不支持config命令，自己搭建的redis服务就没有这限制，感觉是这样，所以phpredisadmin配上databases 参数后就没问题了。

**Comment by kuainiao** [comment]
我看到源码有获取databases参数的属性，应该是 jedis.configGet("databases");这里，我没用过java，不会改，云redis不支持获取这个参数。
	public void command() {
		List<String> dbs = jedis.configGet("databases");
		if(dbs.size() > 0)
			dbAmount = Integer.parseInt(dbs.get(1));
		else
			dbAmount = 15;
	}

	@Override
	public RedisVersion getSupportVersion() {
		return RedisVersion.REDIS_2_0;
	}

**Comment by kuainiao** [comment]
我看到源码有获取databases参数的属性，应该是 jedis.configGet("databases");这里，我没用过java，不会改，云redis不支持获取这个参数。
public void command() {
List dbs = jedis.configGet("databases");
if(dbs.size() > 0)
dbAmount = Integer.parseInt(dbs.get(1));
else
dbAmount = 15;
}

**Comment by caoxinyu** [comment]
jedis.configGet("databases")这个和rename-command CONFIG不是一个东西， jedis.configGet("databases")是用来获取数据库的个数的。腾讯配置了rename-command CONFIG目的就是为了不让你用config命令，这个不是客户端可以控制的。

**Comment by caoxinyu** [comment]
你前面说加上'databases' => 16,这个配置后就避开config命令，是说把database个数设置成16个，就可以使用config命令配置redis了?

**Comment by kuainiao** [comment]
是的，腾讯技术哥叫我把phpredisadmin的database个数设置成16个就正常使用了。
